### ISSUE TITLE
State value to set for "dreame.0.xxxxxxxxx.***" has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by KoMa1978** [TA2k/ioBroker.dreame#3]
Bei jeder API Abfrage durch den Adapter erhälte ich etliche Fehlermeldungen, sowohl für ".remote." als auch für ".status.":

> 2024-08-01 13:44:02.910	info	State value to set for "dreame.0.xxxxxxxxx.status.dust-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.910	info	State value to set for "dreame.0.xxxxxxxxx.status.dust-enable" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.909	info	State value to set for "dreame.0.xxxxxxxxx.status.total-clean-area" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.908	info	State value to set for "dreame.0.xxxxxxxxx.status.total-clean-times" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.906	info	State value to set for "dreame.0.xxxxxxxxx.status.total-clean-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.903	info	State value to set for "dreame.0.xxxxxxxxx.remote.volume" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.863	info	State value to set for "dreame.0.xxxxxxxxx.remote.mult-map-state" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.740	info	State value to set for "dreame.0.xxxxxxxxx.status.auto-water-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.740	info	State value to set for "dreame.0.xxxxxxxxx.status.nowater-tips" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.740	info	State value to set for "dreame.0.xxxxxxxxx.remote.dry-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.739	info	State value to set for "dreame.0.xxxxxxxxx.remote.auto-add-detergent" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.718	info	State value to set for "dreame.0.xxxxxxxxx.remote.carpet-clean" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.704	info	State value to set for "dreame.0.xxxxxxxxx.status.warn-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.704	info	State value to set for "dreame.0.xxxxxxxxx.remote.autowash-switch" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.704	info	State value to set for "dreame.0.xxxxxxxxx.remote.carpet-distinguish" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.704	info	State value to set for "dreame.0.xxxxxxxxx.remote.mop-way" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.703	info	State value to set for "dreame.0.xxxxxxxxx.remote.sensitivity" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.703	info	State value to set for "dreame.0.xxxxxxxxx.remote.child-lock" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.703	info	State value to set for "dreame.0.xxxxxxxxx.remote.custom-enable" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.703	info	State value to set for "dreame.0.xxxxxxxxx.status.mop-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.703	info	State value to set for "dreame.0.xxxxxxxxx.remote.clean-setting" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.703	info	State value to set for "dreame.0.xxxxxxxxx.remote.ai-switch" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.702	info	State value to set for "dreame.0.xxxxxxxxx.status.relocation-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.702	info	State value to set for "dreame.0.xxxxxxxxx.status.keep-sweeper-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.701	info	State value to set for "dreame.0.xxxxxxxxx.remote.carpet-press" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.701	info	State value to set for "dreame.0.xxxxxxxxx.remote.break-point-restart" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.701	info	State value to set for "dreame.0.xxxxxxxxx.status.task-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.701	info	State value to set for "dreame.0.xxxxxxxxx.status.waterbox-status" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.701	info	State value to set for "dreame.0.xxxxxxxxx.remote.cleaning-mode" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.701	info	State value to set for "dreame.0.xxxxxxxxx.status.cleaning-area" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.700	info	State value to set for "dreame.0.xxxxxxxxx.status.cleaning-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.700	info	State value to set for "dreame.0.xxxxxxxxx.status.work-mode" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.700	info	State value to set for "dreame.0.xxxxxxxxx.status.filter-left-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.700	info	State value to set for "dreame.0.xxxxxxxxx.status.filter-life-level" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.700	info	State value to set for "dreame.0.xxxxxxxxx.status.brush-life-level" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.700	info	State value to set for "dreame.0.xxxxxxxxx.status.brush-left-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.699	info	State value to set for "dreame.0.xxxxxxxxx.status.brush-life-level" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.699	info	State value to set for "dreame.0.xxxxxxxxx.status.brush-left-time" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.699	info	State value to set for "dreame.0.xxxxxxxxx.status.charging-state" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.699	info	State value to set for "dreame.0.xxxxxxxxx.status.battery-level" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.699	info	State value to set for "dreame.0.xxxxxxxxx.remote.mode" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.698	info	State value to set for "dreame.0.xxxxxxxxx.status.fault" has to be type "string" but received type "number"
> 2024-08-01 13:44:02.697	info	State value to set for "dreame.0.xxxxxxxxx.status.status" has to be type "string" but received type "number"

Kann man das irgendwie korrigieren? Manuell in meine installation? Im Adapter bei der Objektanlage?

Oder einfach das Log-Level von Info auf Warn hochstellen?

Besten Dank,
 KoMa1978

**Comment by TA2k** [comment]
auch mit der letzten github?

**Comment by KoMa1978** [comment]
Die v0.0.1 vor ner knappen Woche vom GitHub installiert.

**Comment by TA2k** [comment]
Bitte erneut installieren

**Comment by KoMa1978** [comment]
Heute gemacht ... gleiches Ergebnis: Es kommen immernoch einige dieser Meldungen:

State value to set for "dreame.0.xx.status.work-mode" has to be type "string" but received type "number"
State value to set for "dreame.0.xx.status.battery-level" has to be type "string" but received type "number"
State value to set for "dreame.0.xx.status.work-mode" has to be type "string" but received type "number"
State value to set for "dreame.0.xx.status.battery-level" has to be type "string" but received type "number"
State value to set for "dreame.0.xx.status.work-mode" has to be type "string" but received type "number"

**Comment by KoMa1978** [comment]
Nach ein paar Tagen und einigen Reinigungen wird gefühlt jeder Wert mit dem Fehler beanstandet. Generell läuft der Adapter wunderbar, es sind tatsächlich nur die Meldungen bzgl der fehlerhaften Datentypen.

**Comment by KoMa1978** [comment]
Ich habe jetzt einen 2. Dreame eingebunden und aktuell werden die Fehler für beide Sauger protokolliert.

**Comment by TA2k** [comment]
bitte GitHub version testen

**Comment by KoMa1978** [comment]
Hi, sieht besser aus, vielen Dank. Allerdings kommt der mit der 0.2.0 wieder:


```
dreame.0 | 2025-01-03 11:06:16.012 | info | State value to set for "dreame.0.837102548.map.maps.current.image" has to be type "image" but received type "string"
dreame.0 | 2025-01-03 11:06:15.971 | info | State value to set for "dreame.0.790338101.map.maps.current.image" has to be type "image" but received type "string"
dreame.0 | 2025-01-03 11:06:15.934 | warn | Object xxxxxx.map.maps.current.image is invalid: obj.common.type has an invalid value (image) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
dreame.0 | 2025-01-03 11:06:15.925 | warn | Object xxxxxx.map.maps.current.image is invalid: obj.common.type has an invalid value (image) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!

```
