### ISSUE TITLE
Device list error: TypeError: Cannot set properties of undefined (setting '2-1')

### ISSUE THREAD

**Issue by tipp88** [TA2k/ioBroker.dreame#8]
Dreame L40 Ultra

following warnings/errors in current Github version:
![image](https://github.com/user-attachments/assets/158ba764-f97a-40a7-9144-df301e57f5f7)

Besides this, the already repoted problem about data type mismatch still exists: 
_has to be type "string" but received type "number"_

Regardless, the adapter is working fine and I appreciate the work by you guys, thanks!

**Comment by TA2k** [comment]
fixed
